# Generated by Django 2.2.2 on 2019-06-22 09:57

import os
from django.db import migrations
from django.contrib.sites.models import Site

class Migration(migrations.Migration):

    def seeding(apps, schema_editor):
        default_site = Site(id=1, domain=os.environ['DOMAIN'], name=os.environ['APP_NAME'])
        default_site.save()

    dependencies = [
        ('chat', '0001_initial'),
        ('sites', '__first__'),
    ]

    operations = [
        migrations.RunPython(seeding),
    ]
